config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # get 'about', to: 'pages#about'
  resources :lists, only: [:index, :show, :new, :create, :destroy] do
    resources :invites, only: [:new, :create]
    patch '/invites/:id', to: 'invites#accept', as: :invite
    resources :items, only: [:new, :create, :destroy]
  end
  resources :invites, only: [:index, :destroy]
  resources :items, only: [:index, :create, :edit, :update] do
      member do
        patch :as_done
        patch :not_done
      end
    end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/invite.rb
class Invite < ApplicationRecord
  belongs_to :list
  belongs_to :user

  attr_accessor :email
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list
  belongs_to :user
  has_many :users, through: :lists

  validates :title, :quantity, presence: true
  # validates :status, default: false

end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :items, dependent: :destroy
  has_many :invites
  has_many :users, through: :invites, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :invites
  has_many :lists
  has_many :items

  has_one_attached :avatar
  validates :first_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :avatar])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :avatar])
  end

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  protect_from_forgery with: :null_session

  def index
    @invites = current_user.invites
    @pending_invites = @invites.select { |invite| invite.accepted != true}.uniq
    @accepted_invites = @invites.select { |invite| invite.accepted == true }.uniq
  end

  def new
    @invite = Invite.new
    @list = List.find(params[:list_id])
  end

  def create
    @invite = Invite.new(invite_params)
    @list = List.find(params[:list_id])
    @invite.list = @list
    #Getting email from form
    email = params[:invite][:email]
    #Getting user from email submitted by the user
    user = User.find_by(email: email)
    if user
      @invite.user = user
    end
    if @invite.save
      flash.notice = "#{@invite.user.first_name} has been invited to #{@invite.list.name}"
    else
      flash.alert = "#{email} doesn't have a ListIn account yet."

    end
    redirect_to list_path(@list.id)
  end

  def accept
    # raise
    @invite = Invite.find(params[:id])
    @invite.accepted = true
    if @invite.save
      flash.notice = "You successfully joined #{@invite.list.name}"
      redirect_to list_path(@invite.list)
    end
  end

  private

  def invite_params
    params.require(:invite).permit(:list_id)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def new
    @item = Item.new
    @item = Item.find(params[:item_id])
  end

  def create
    @item = Item.new(item_params)
    @item.user_id = current_user.id
    @list = List.find(params[:list_id])
    @item.list_id = @list.id
    if @item.save
      flash.notice = "#{@item.title} has been added to your list"
      redirect_to list_path(@list.id)
    else
      render :new
    end
  end

  def not_done
    @item = Item.find(params[:id])
    @item.done = false
    if @item.save
      flash.notice = "#{@item.title} (#{@item.quantity}) is back in your list."
      redirect_to list_path(@item.list)
    end
  end

  def as_done
    @item = Item.find(params[:id])
    @item.done = true
    if @item.save
      flash.notice = "#{@item.title} has been added to you basket."
      redirect_to list_path(@item.list)
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(params[:id])
    redirect_to list_path(@item.list)
  end


  def destroy
    @item = Item.find(params[:list_id])
    # @item.user_id = current_user.id
    @item.destroy
    flash.notice = "#{@item.title} has been removed."
    redirect_to list_path(@item.list)
  end

  private

  def item_params
    params.require(:item).permit(:list_id, :user_id, :status, :title, :quantity)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    # @all_lists = List.all
    # @lists_invitations = current_user.invites.select {|invite| invite.accepted?}
    # @all_user_lists = @all_lists.select { |list| list.user_id == current_user.id || !list.invites.select { |invite| invite.accepted? && list.user_id == current_user.id}.empty? }
    # @lists = @all_user_lists.uniq.sort
    @lists_invitations = current_user.invites.select { |invite| invite.accepted?}.map {|invite| invite.list}.uniq.sort {|a,b| b.created_at <=> a.created_at}
    @lists = current_user.lists.uniq.sort {|a,b| b.created_at <=> a.created_at}

  end


  def show
    @list = List.find(params[:id])
    @invite = Invite.new
    @item = Item.new
    @items = @list.items
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.user_id = current_user.id
    if @list.save
      flash.notice = "#{@list.name} has been created"
      redirect_to list_path(@list.id)
    else
      render :new
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.user_id = current_user.id
    @list.destroy
    flash.notice = "#{@list.name} has been removed."
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/invites/_invite_card.html.erb
<div class="" >
  <% invites.each do |invite| %>
    <div class="invite-card">
        <div class="list-card-1 row" >
          <div class="avatar-card owner-avatar-invite-card">
            <% if invite.list.user.avatar.attached? %>
              <%= cl_image_tag invite.list.user.avatar.key, width: 50, height: 50, crop: :fill, style: "border-radius: 50%;", class: "image" %>
            <% else %>
              <%= image_tag("user-avatar.png", width: 50, height: 50, crop: :fill, style: "border-radius: 50%;", class: "image") %>
            <% end %>

              <div class="owner-name-invite-card">
                <%= invite.list.user.first_name %>
              </div>
          </div>

          <div>
            <h3><%= invite.list.name %></h3>
          </div>
        </div>

        <div class="list-card-2 row" >
          <div class="list-invitees">
            <% invite.list.invites.each do |invite| %>
              <% if invite.user.avatar.attached? %>
                <%= cl_image_tag invite.user.avatar.key, width: 30, height: 30, crop: :fill, style: "border-radius: 50%;",class: "list-invitee" %>
              <% else %>
                <%= image_tag("user-avatar.png", class: "list-invitee") %>
              <% end %>
            <% end %>
          </div>

        </div>
          <% if invite.accepted != true %>
            <div class="accept-invite">
              <%= link_to list_invite_path(invite.list.id, invite.id), remote: true,
                                                                      method: :patch do %>
                <span class='button-interactive '>Accept</span>
              <% end %>
            </div>
          <% end %>
      <% end %>
    </div>
</div>

app/views/invites/_new_invite_modal.html.erb
<div class="modal fade" id="inviteModal" tabindex="-1" role="dialog" aria-labelledby="inviteModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered offset-top-modal modal-list-show" role="document">
    <div class="modal-content modal-list-show-radius">
      <div class="modal-header">
        <h5 class="modal-title" id="inviteModalLabel">Invite a friend to join <%=@list.name%></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span class="close-invite"aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= simple_form_for [@list, @invite], remote: true do |f| %>
      <div class="modal-body">
        <div class="form-wrapper" id="invite-form-div">
            <%= f.input :email, label: 'Please enter an email address to invite a friend', :placeholder => 'listin@listin.com' %>
        </div>
      </div>
        <div class="modal-footer">
          <%= f.button :submit, 'Send invite', class: "button-send-invite" %>
        </div>
        <% end %>
    </div>
  </div>
</div>

app/views/invites/index.html.erb
<div>
    <div class="container text-center">
      <div class="index-title mb-5">
        <h1 class="big-title">Your invites</h1>
      </div>
  <div class="mt-2 user-invites">

    <div >
      <% if @pending_invites.count == 0 %>
        <p class="invite-content medium-title"> You have no pending invites...</p>

        <div class="nav-item">
          <%= link_to "your lists", lists_path, class: "button"%>
        </div>
      <% else %>
        <h2 class="medium-title">My pending invites <%= "(#{@pending_invites.count})" %> </h2>

          <div class="container invites_cards">
            <div>
            <%= render "invite_card", invites: @pending_invites%>
            </div>
            <div class="nav-item-list-index">
              <%= link_to "your lists", lists_path, class: "button-yourlist"%>
            </div>
          </div>

      <% end %>
    </div>

  </div>
    </div>
  </div>
</div>

app/views/invites/new.html.erb
<h1>Create an invite for your <%= @list.title %> list</h1>

app/views/items/_list.html.erb
<div class="item-quant">
  <% items.each do |item| %>
    <% if item.done !=true %>

      <div class="one-item row">
        <div class="list-flex-item">
        <% if item.user_id == current_user.id %>
          <%= link_to list_item_path(item), method: :delete,
                                            class: "delete-item",
                                            data: { confirm: "Delete #{item.title}?" } do %>
              <span class="button-delete">
                <i class="fas fa-trash-alt"></i>
              </span>
            <% end %>
          <% end %>
        </div>

    <% if item.user_id == current_user.id %>
      <div class="list-flex-item row text-item-trash">
        <div><%= item.title %></div>
        <div><%= item.quantity %></div>
      </div>
      <% else %>
      <div class="list-flex-item row text-item">
        <div><%= item.title %></div>
        <div><%= item.quantity %></div>
      </div>
    <% end %>

        <div class="list-flex-item">
            <%= link_to as_done_item_path(item), remote: true,
                                        method: :patch,
                                        class: "asdone-item" do %>
              <span class="button-caddie">
                <i class="fas fa-shopping-cart"></i>
              </span>
            <% end %>
        </div>
      </div>

    <% elsif item.done == true %>
    <div class="one-item row">

      <mark>
      <div class="list-flex-item row text-item">
          <div><%= item.title %></div>
          <div><%= item.quantity %></div>
      </div>
      </mark>

      <div class="list-flex-item">
        <%= link_to not_done_item_path(item), remote: true,
                                      method: :patch,
                                      class: "back-item-notdone",
                                      data: { confirm: "#{item.title} (#{item.quantity}) back in your list?" } do %>
            <span class="button-back-item">
              <i class="fas fa-undo"></i>
            </span>
          <% end %>
      </div>

    </div>
  <% end %>
  <% end %>
</div>

app/views/items/_new.html.erb
<div class="container row new-item">
  <%= simple_form_for [@list, @item], remote: true do |f| %>
    <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
      <div class="form-wrapper item-form">
        <div class="row add-item-bar">
          <%= f.input :title,
                      :placeholder => "chocolate",
                      label: false,
                      class: "item-input" %>
          <%= f.input :quantity,
                      :placeholder => '200g',
                      label: false,
                      class: "item-input"%>
          <%= f.button :submit, '+',
                      class: "button-add-item"%>
        </div>
      </div>
  <% end %>
</div>

app/views/items/new.html.erb
<h1>Add an item and quantity</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Listin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

  <%= favicon_link_tag asset_path('logolistin.png') %>
  <meta property="og:image" content="https://res.cloudinary.com/clotou/image/upload/e_cartoonify,r_2/v1629728076/cdf86a55-edc9-4df8-83b5-e7617dd5d32d_ezvu26.jpg" />
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/lists/_index.html.erb
<h1>All the lists are here</h1>
<ul class="list-group">
<% @lists.each do |list| %>
<li class="list-group-item"><%=list.name%></li>
<% end %>
</ul>

app/views/lists/_show.html.erb
<h1>
<%= @list.name %>
</h1>
<ul>
  <% @items.each do |item| %>
  <li><%= item.title %><%= item.quantity %><%= item.status %></li>
</ul>

app/views/lists/index.html.erb
<div class="container">
  <h1 class="big-title">All the lists are here</h1>
  <ul class="list-group">
  <%  @lists.each do |list| %>
  <li class="button-list-owner"><%= link_to "#{list.name}", list_path(list)%></li>
    <% end %>
  <%  @lists_invitations.each do |list| %>
  <li class="button"><%= link_to "#{list.name}", list_path(list)%></li>
    <% end %>
  </ul>
</div>

app/views/lists/new.html.erb
<div class="container">
  <h1 class="big-title">Create you list here!</h3>
  <div class="form-wrapper" id="booking-form-div">
    <%= simple_form_for(@list) do |f| %>
      <%= f.input :name, required: false, placeholder: "groceries" %>
      <%= f.submit 'Create'%>
    <% end %>
  </div>
</div>

app/views/lists/show.html.erb
<div class="container">
  <div class="row title-list">
    <% if @list.user == current_user %>
      <%= link_to list_path(@list), method: :delete,
                                    class: "delete-list",
                                    data: { confirm: "Delete #{@list.name}?" } do %>
          <span class="button-delete" id="list-trash">
            <i class="fas fa-trash-alt"></i>
          </span>
          <% end %>
      <% else %>

      <% if @list.user.avatar.attached? %>
        <span class="owner-avatr-list-title"><%= cl_image_tag @list.user.avatar.key, width: 50, height: 50, crop: :fill, style: "border-radius: 50%;", class: "image" %></span>
      <% else %>
        <%= image_tag("user-avatar.png", width: 50, height: 50, crop: :fill, style: "border-radius: 50%;", class: "image") %>
      <% end %>

    <% end %>


    <h1 class="medium-title">
    <%= @list.name %>
    </h1>
  </div>

  <div class="avatar-list">
    <div class="list-invitees-show row">
      <div class="button-add-invites " data-toggle="modal" data-target="#inviteModal">
          <div data-toggle="tooltip" data-placement="top" title="Invite a friend" class="tooltip-add">
            <i class="fas fa-plus"></i>
          </div>
      </div>
      <% @list.invites.each do |invite| %>

        <div class="list-invitees-show row">

            <% if invite.user.avatar.attached? %>
              <% if invite.accepted?%>
                <%= cl_image_tag invite.user.avatar.key, width: 50, height: 50, crop: :fill, class: "list-invitee-show" %>
              <% else %>
                <%= cl_image_tag invite.user.avatar.key, width: 50, height: 50, crop: :fill, class: "list-invitee-show unaccepted-invite"%>

              <% end %>
            <% else %>
              <%= image_tag("user-avatar.png", class: "list-invitee-show") %>
            <% end %>

        </div>

      <% end %>
    </div>
  </div>

  <%= render "invites/new_invite_modal" %>

  <div>
    <%= render "items/new" %>
  </div>




  <div>
    <h4 class="my-item-title"> My items </h4>
    <!-- not done items -->
    <div>
      <%= render "items/list", items: @list.items.select {|item| item.done != true}.sort%>
    </div>
  </div>

  <div>
    <h4 class="basket-item-title"> In my basket </h4>
    <!-- items done-->
    <div class="all-asdone-items">
    <%= render "items/list", items: @list.items.select {|item| item.done == true}.sort%>
  </div>
</div>

app/views/pages/home.html.erb
<!--<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

class="collapse navbar-collapse" id="navbarSupportedContent"-->
<div class="container">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Create list", new_list_path, class: "button" %>
        </li>
        <li class="nav-item">
          <%= link_to "My lists", lists_path, class: "button" %>
        </li>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "button" %>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="marketing-cards">

    <div class="marketing-card-1">
      <div class="card-marketing-top">
      <h2 class="marketing-title">Interactive</h2>
      <p class="marketing-text">You will quickly know and inform about what to buy.</p>
      </div>
      <div class="card-marketing-bottom">
      <img src="https://images.unsplash.com/photo-1552664862-db5607e91378?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8c2hhcmluZ3xlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60" alt="interactive">
      </div>
    </div>

    <div class="marketing-card-2">
      <div class="card-marketing-top">
        <h2 class="marketing-title">Share</h2>
        <p class="marketing-text">Your list will never be easier to share with your friends.</p>
      </div>
      <div class="card-marketing-bottom">
        <img src="https://images.unsplash.com/photo-1604881988758-f76ad2f7aac1?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2071&q=80" alt="share">
      </div>
    </div>

    <div class="marketing-card-3">
      <div class="card-marketing-top">
        <h2 class="marketing-title">Never forget</h2>
        <p class="marketing-text">Your won't forget anything anymore in your groceries.</p>
      </div>
      <div class="card-marketing-bottom">
        <img src="https://images.unsplash.com/photo-1620247405684-8352d6d7ce09?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2069&q=80" alt="share">
      </div>
    </div>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
  </div>
  <div class="footer-copyright">
     <p>List-In</p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-listin">
  <div>
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logolistin.png" %>
    <% end %>
  </div>
  <div>
    <% if user_signed_in?%>
      <div class="nav-item dropdown dropdown-logged ">

        <% if current_user.avatar.attached? %>
          <div class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" type="button">
            <%= cl_image_tag current_user.avatar.key, class:"avatar" %>
          </div>
        <% else %>
          <i class='fas fa-user-circle avatar dropdown-toggle' id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" type="button" ></i>
      <% end %>

          <%= "<i class='fas fa-dot-circle dot-invite'></i>".html_safe if current_user.invites.select {|invite| invite.accepted.nil?}.count!=0%>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <div class = "notification-invite">
              <%= link_to  "My invites", invites_path, class: "dropdown-item" %>
              <%= "<i class='fas fa-dot-circle dot-dropdown'></i>".html_safe if current_user.invites.select {|invite| invite.accepted.nil?}.count!=0%>
            </div>
            <%= link_to "My lists", lists_path, class: "dropdown-item" %>
            <%= link_to "Edit your profile", edit_user_registration_path, class: "dropdown-item"  %>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>

    <% else %>

      <div class="nav-item dropdown">
        <div>
        <i class="fas fa-user-circle avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Sign in", user_session_path, class: "dropdown-item" %>
            <%= link_to "Sign up", new_user_registration_path, class: "dropdown-item" %>
          </div>
        </div>
      </div>
    <% end %>

    </div>

  </div>

</div>